### ISSUE TITLE
No se puede cambiar la lengua de la interfaz

### ISSUE THREAD

**Issue by amosbatto** [KetanoLab/Nusimi-android#1]
En algunos celulares, no puedo cambiar la lengua de la interfaz a quechua, aymara y portugués en Settings > Select Language. Si yo selecciono una de estas lenguas, la interfaz cambia a inglés. Sólo puedo cambiar la interfaz de Nusimi a español o Inglés.

En mis celulares que utilizan LineageOS, no observo este problema, pero lo he visto en un Samsung Galaxy Note 10.1 con Android 5.0, un Samsung J7 con Android 10 y un Xiaomi con Android 10. Asumo que los skins personalizados de Samsung y Xiaomi causan el problema.

**Comment by KetanoLab** [comment]
this has already been fixed in 1.0.07  The issue was that  playstore bundle only deploys user system languages, so Ive fixed that to deploy all resources changing the playstore bundle metadata
